# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: T7 Lee School
email: t7leeschool@example.com
description: >-
  T7 Lee resources curated by the Lee Discord
baseurl: "/"
url: "https://t7leeschool.github.io"
github_username: t7leeschool
markdown: kramdown
kramdown:
  parse_block_html: true
  parse_span_html: true
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - t7leeschool.sublime-project
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Need this so that the _pages dir isn't skipped
collections:
  pages:
    output: true
    permalink: /:path

# Set the default layout to all pages
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
